name = "my-portfolio"
main = "./.next/standalone/server.js"
compatibility_date = "2024-02-13"

[vars]
NEXT_PUBLIC_NOTION_API_KEY=ntn_d20846464906T75ABKTiHgZTfGUAF7rRZtjRv2lZ4KC4wd
NEXT_PUBLIC_NOTION_DATABASE_ID=19107c412e5a8073bf23f7e4509d277e
NEXT_PUBLIC_NOTION_TAGS_DATABASE_ID=19107c412e5a80399b33c964fd7fc07e
NEXT_PUBLIC_NOTION_PROFILE_DB_ID=19107c412e5a80d1b8eae94214cd44f2